# Generated by Django 3.2 on 2021-04-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0011_auto_20210408_2207'),
        ('institucional', '0012_auto_20210409_1009'),
    ]

    operations = [
    ]
