# Generated by Django 3.1.7 on 2021-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0004_auto_20210408_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='quemsomos',
            name='imageQS',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
    ]
