# Generated by Django 3.1.7 on 2021-04-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0007_auto_20210408_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painel',
            name='imagePainel',
            field=models.ImageField(blank=True, upload_to='../pagina/static/imagem'),
        ),
    ]
