# Generated by Django 3.1.7 on 2021-04-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0008_auto_20210408_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painel',
            name='imagePainel',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
    ]
