# Generated by Django 3.1.7 on 2021-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0009_auto_20210408_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painel',
            name='imagePainel',
            field=models.ImageField(blank=True, upload_to='pagina/static/imagens/'),
        ),
    ]
