# Generated by Django 2.2.20 on 2021-04-11 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0013_merge_0011_auto_20210408_2207_0012_auto_20210409_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='celular',
            field=models.CharField(max_length=13, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_modificacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=12, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='painel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='painel',
            name='imagePainel',
            field=models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='painel',
            name='sloganPainel',
            field=models.CharField(max_length=255, verbose_name='Slogan do painel'),
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='descricaoPortifolio',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='imagePortifolio',
            field=models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='apresentacao',
            field=models.TextField(verbose_name='Apresentação'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='data_modificacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='imageQuemSomos',
            field=models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='redessociais',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='redessociais',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Link de aceeso à rede'),
        ),
        migrations.AlterField(
            model_name='redessociais',
            name='nomeRS',
            field=models.CharField(max_length=30, verbose_name='Nome na rede'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='descrição_do_servico',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='imageServico',
            field=models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do serviço'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='preço',
            field=models.CharField(max_length=13, verbose_name='Preço'),
        ),
    ]
