# Generated by Django 2.2.20 on 2021-04-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0014_auto_20210411_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='redesSociais',
        ),
    ]
