# Generated by Django 2.2.20 on 2021-04-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0016_auto_20210411_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quemsomos',
            name='apresentacao',
        ),
        migrations.RemoveField(
            model_name='quemsomos',
            name='imageQuemSomos',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='imageServico',
        ),
        migrations.AddField(
            model_name='portifolio',
            name='nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome do aluno'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='nota',
            field=models.IntegerField(blank=True, default=0, verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='quemsomos',
            name='oferecimento',
            field=models.TextField(blank=True, verbose_name='O que oferecemos'),
        ),
        migrations.AddField(
            model_name='quemsomos',
            name='oque_fazemos',
            field=models.TextField(blank=True, verbose_name='O que fazemos'),
        ),
        migrations.AddField(
            model_name='quemsomos',
            name='valores',
            field=models.TextField(blank=True, verbose_name='Valores'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='celular',
            field=models.CharField(blank=True, max_length=13, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='painel',
            name='sloganPainel',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slogan do painel'),
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='descricaoPortifolio',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='descrição_do_servico',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome do serviço'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='preço',
            field=models.IntegerField(blank=True, default=0, verbose_name='Preço'),
        ),
    ]
