# Generated by Django 2.2.20 on 2021-04-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0017_auto_20210411_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quemsomos',
            old_name='titulo',
            new_name='Titulo',
        ),
    ]
