# Generated by Django 2.2.20 on 2021-04-12 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0018_auto_20210412_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quemsomos',
            name='Titulo',
        ),
    ]
