# Generated by Django 2.2.20 on 2021-04-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0019_remove_quemsomos_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quemsomos',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Título'),
        ),
    ]
