# Generated by Django 2.2.20 on 2021-04-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0020_quemsomos_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicos',
            old_name='preço',
            new_name='preco_servico',
        ),
    ]
