# Generated by Django 2.2.20 on 2021-04-13 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0021_auto_20210412_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan_home', models.CharField(blank=True, max_length=255, verbose_name='Slogan do Home')),
                ('imageHome', models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem')),
                ('descricao_card', models.TextField(blank=True, verbose_name='Descrição do Card')),
                ('preco_card', models.IntegerField(default=0, verbose_name='Preço do Card')),
                ('data_modificacao', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data de modificação')),
            ],
        ),
        migrations.CreateModel(
            name='pacotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_pacote', models.CharField(max_length=30, verbose_name='Duração do Pacote')),
                ('quantidade_parcelas', models.IntegerField(default=0, verbose_name='Quantidade de parcelas')),
                ('desconto', models.IntegerField(default=0, verbose_name='Porcentagem de desconto')),
                ('atributos_pacote', models.TextField(blank=True, verbose_name='Atributos do pacote')),
                ('data_modificacao', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data de modificação')),
            ],
        ),
        migrations.DeleteModel(
            name='contato',
        ),
        migrations.DeleteModel(
            name='painel',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='preco_servico',
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='valores',
            field=models.TextField(blank=True, verbose_name='Valores da instituição'),
        ),
    ]
