# Generated by Django 2.2.20 on 2021-04-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0022_auto_20210412_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='preco_card',
            field=models.FloatField(default=0, verbose_name='Preço do Card'),
        ),
    ]
