# Generated by Django 2.2.20 on 2021-04-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0023_auto_20210413_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='imageHome',
        ),
        migrations.RemoveField(
            model_name='home',
            name='slogan_home',
        ),
        migrations.AddField(
            model_name='home',
            name='quantidade_parcelas',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Parcelas'),
        ),
        migrations.AddField(
            model_name='pacotes',
            name='valor_a_vista',
            field=models.FloatField(default=0, verbose_name='Valor à vista'),
        ),
        migrations.AddField(
            model_name='pacotes',
            name='valor_parcela',
            field=models.FloatField(default=0, verbose_name='Valor da parcela'),
        ),
    ]
