# Generated by Django 2.2.4 on 2021-04-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0024_auto_20210413_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacotes',
            name='atributos_pacote',
        ),
        migrations.AddField(
            model_name='servicos',
            name='logo_servico',
            field=models.ImageField(blank=True, upload_to='imagens/', verbose_name='Logo do serviço'),
        ),
    ]
