# Generated by Django 2.2.4 on 2021-04-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0025_auto_20210414_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quemsomos',
            name='titulo',
        ),
    ]
