# Generated by Django 2.2.20 on 2021-04-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0026_remove_quemsomos_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicos',
            old_name='logo_servico',
            new_name='logoServico',
        ),
    ]
